hosts:
  media-server-2024:
    ip: 192.168.1.177
    role: docker
    os: debian

  rpi4:
    ip: 192.168.1.194
    role: docker
    os: raspberrypi

  pihole:
    ip: 192.168.1.217
    role: dns
    os: raspberrypi
